### ISSUE TITLE
routines are leaked when permissions are closed

### ISSUE THREAD

**Issue by Sean-Der** [pion/turnc#7]
I am adding a E2E test in `pion/ice` that asserts no routines are leaked.

Even after I close all permissions I am getting https://gist.github.com/Sean-Der/dbd0ed46c9d05798bdf4ecf66224fb07

I don't see a way to close a `Allocation` so these might be attached to that. Haven't really dived in yet

**Comment by Sean-Der** [comment]
@ernado mind taking a quick look at this? Is there any additional cleanup I should be calling with the `turnc` public API?

**Comment by ernado** [comment]
Will take a look.
Can you please share the e2e tests with me so I can debug?

**Comment by Sean-Der** [comment]
Yep!

If you grab this branch https://github.com/pion/ice/pull/66

Do `go test -run TestRelayOnlyConnection`
