### ISSUE TITLE
CPU catches fire when turn server is offline

### ISSUE THREAD

**Issue by thetooth** [pion/turnc#9]
Not sure if this is in the stun package or this one, but if pions is configured with a turn server that happens to be offline it very aggressively tries to read the closed socket. If the turn sever is alive then there is no issue.

```
Showing nodes accounting for 65.23s, 84.59% of 77.11s total
Dropped 66 nodes (cum <= 0.39s)
Showing top 10 nodes out of 17
      flat  flat%   sum%        cum   cum%
    12.12s 15.72% 15.72%     12.12s 15.72%  runtime.unlock
    11.43s 14.82% 30.54%     11.43s 14.82%  runtime.lock
    11.39s 14.77% 45.31%     34.94s 45.31%  runtime.chanrecv
     5.34s  6.93% 52.24%     56.76s 73.61%  net.(*pipe).Read
     5.21s  6.76% 58.99%     40.15s 52.07%  runtime.selectnbrecv
     4.56s  5.91% 64.91%     47.02s 60.98%  net.(*pipe).read
     4.38s  5.68% 70.59%      6.65s  8.62%  runtime.ifaceeq
     4.21s  5.46% 76.05%     42.46s 55.06%  net.isClosedChan
     3.49s  4.53% 80.57%     37.56s 48.71%  github.com/pion/turnc.(*Client).readUntilClosed
     3.10s  4.02% 84.59%     29.69s 38.50%  github.com/pion/stun.(*Message).ReadFrom
```

**Comment by Sean-Der** [comment]
nice catch @thetooth 

It looks like we ignore `io.EOF` not sure why though https://github.com/pion/turnc/blob/master/client.go#L176

**Comment by Sean-Der** [comment]
can you confirm that you are getting `io.EOF`, @ernado any thoughts on this?

**Comment by Sean-Der** [comment]
@thetooth are you able to flip that `continue` to a `break`, and see if that fixes the issue?

@ernado any thoughts on this?

**Comment by Sean-Der** [comment]
@thetooth 

I haven't been unable to reproduce this, mind trying out that fix and we can try to land it?

thanks

**Comment by thetooth** [comment]
Sorry for no updates have been super busy. Yeah changing to a break resolves some of the issue (4 cores spinning instead of 12) and is indeed EOF error. The real problem is in the stun package, again in readUntilClosed, here we have one spicy loop. There is no exit path when ReadFrom emits an error and instead it just spins, I added an else statement that just returns and it fixes the issue.

**Comment by Sean-Der** [comment]
No worries, now I am the one that is slow :(

@enobufs is taking this on, we are moving the client to `pion/turn`. We should have something really soon.

**Comment by Sean-Der** [comment]
@thetooth 

It is look like next week we should have something! I will reach out when we have moved over, and we can figure out what needs to be fixed/addresses. We had a couple issues that we weren't able to fix cleanly.

thanks!
